Prueba4/Prueba3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Prueba4/app/urls.py
from django.urls import path, include
from .views import home, productos, formulario, agregar_producto, listar_producto, modificar_producto, eliminar_producto,\
    registro, ProductoViewset, TipoViewset
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewset)
router.register('tipo', TipoViewset)

urlpatterns = [
    path('', home, name="home"),
    path('productos/', productos, name="productos"),
    path('formulario/', formulario, name="formulario"),
    path('agregar-producto/', agregar_producto, name="agregar_producto"),
    path('listar-producto/', listar_producto, name="listar_producto"),
    path('modificar-producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('registro/', registro, name="registro"),
    path('api/', include(router.urls)),
]

Prueba4/app/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.forms import PasswordInput

# Create your models here.
class Tipo(models.Model): #TIPO = ARBUSTO, FLORES, MACETEROS, TIERRAS
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model): #PRODUCTO = NOMBRE, ESPECIE, DESCRIPCION, PRECIO, NOVEDAD, TIPO, FECHA DE ENTRADA A TIENDA
    nombre = models.CharField(max_length=50)
    especie = models.CharField(max_length=50)
    descripcion = models.TextField() 
    precio = models.IntegerField()
    novedad = models.BooleanField()
    tipo = models.ForeignKey(Tipo, on_delete=models.PROTECT)
    fecha_entrada = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre

###################
#FORMULARIO

opciones_pais = [
    [0, "Chile"],
    [1, "Argentina"],
    [2, "España"]
]

opciones_region = [
    [0, "Antofagasta"],
    [1, "Valparaíso"],
    [2, "Araucanía"]
]

opciones_flores = [
    [0, "Lilys"],
    [1, "Girasoles"],
    [2, "Rosas"],
    [3, "Tulipanes"],
    [4, "Jasmines"],
    [5, "Gladiolas"],
    [6, "Hibiscus"],
    [7, "Violetas"]
]

opciones_espe = [
    [0, "Arbustos"],
    [1, "Flores"],
    [2, "Maceteros"],
    [3, "Tierra de Hojas"]
]

class Formulario(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    edad = models.IntegerField()
    direccion = models.CharField(max_length=100)
    tipo_pais = models.IntegerField(choices=opciones_pais)
    tipo_region = models.IntegerField(choices=opciones_region)
    tipo_flores = models.IntegerField(choices=opciones_flores)
    tipo_especializacion = models.IntegerField(choices=opciones_espe)
    correo = models.EmailField()
    contraseña = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

Prueba4/app/templates/app/items/agregar.html
<!DOCTYPE html>
<html lang="EN">

<head>
    <meta charset="UTF-8">
    <title>Agregar Producto</title>
    <meta name="viewport" content="eidth=device-width, initial-scale=1">
    <!-- Hipervinculo a CSS ####################################################################-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/P1Css/Css3.css' %}">
    <!-- Invocar Formulario ####################################################################-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

{% load crispy_forms_tags %}

<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'app/P1Img/Logo Icon.png' %}" alt="Icon" width="125" height="125"
                        class="d-inline-block">
                    Jardinería
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <!--
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                -->

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Volver Atrás</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Nuestros Productos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'productos' %}#arbusto">Arbustos</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#flores">Flores</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#maceteros">Maceteros</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#tierras">Tierra de Hojas</a>
                                </li>
                            </ul>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}#nosotros">¿Quiénes Somos?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'formulario' %}">Únete a Nosotros</a>
                        </li>
                        <!--
                        {% if perms.app.add_producto %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'agregar_producto' %}">Agregar Productos</a>
                        </li>
                        {% endif %}
                        -->
                        {% if perms.app.view_producto %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'listar_producto' %}">Listado Productos</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">@{{ user.username }}</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registro' %}">Regístrate Ahora</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="row">
        <div class="col-12 col-md-8 offset-md-2">
            <div class="card" id="formulario">

                <div class="card-title">
                    <h2 style="font-weight: bold; color: brown;">AGREGAR PRODUCTO</h2>
                </div>

                <div class="card-body">
                    <div class="container">

                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}

                            <table>
                                {{ form | crispy }}
                            </table>
                            <hr>

                            <!--
                            <br>
                            <center>
                                <h2 style="font-weight: bold; color:rgb(255, 145, 0)">{{mensaje}}</h2>
                            </center>
                            -->

                            <br>
                            <div class="d-flex justify-content-end">
                                <input type="reset" value="Cancelar" class="btn btn-secondary">
                                &nbsp;
                                <input type="submit" value="Agregar" class="btn btn-primary">
                            </div>

                            <!-- INCORPORACION SCRIPT SWEET ALERT ######################################-->
                            <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

                            {% if messages %}
                            {% for m in messages %}
                            <script>
                                Swal.fire({
                                    "title": "Felicidades",
                                    "text": "{{m}}",
                                    "icon": "success"
                                })
                            </script>
                            {% endfor %}
                            {% endif %}

                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>

    {% block js %}
    <!-- SCRIPT SEPARADOR ######################################################################-->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
    </script>
    {% endblock %}

</body>

</html>

Prueba4/app/templates/app/items/listar.html
<!DOCTYPE html>
<html lang="EN">

<head>
    <meta charset="UTF-8">
    <title>Listar Producto</title>
    <meta name="viewport" content="eidth=device-width, initial-scale=1">
    <!-- Hipervinculo a CSS ####################################################################-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/P1Css/Css3.css' %}">
    <!-- Invocar Formulario ####################################################################-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'app/P1Img/Logo Icon.png' %}" alt="Icon" width="125" height="125"
                        class="d-inline-block">
                    Jardinería
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <!--
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                -->

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Volver Atrás</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Nuestros Productos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'productos' %}#arbusto">Arbustos</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#flores">Flores</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#maceteros">Maceteros</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#tierras">Tierra de Hojas</a>
                                </li>
                            </ul>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}#nosotros">¿Quiénes Somos?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'formulario' %}">Únete a Nosotros</a>
                        </li>
                        {% if perms.app.add_producto %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'agregar_producto' %}">Agregar Productos</a>
                        </li>
                        {% endif %}
                        <!--
                        {% if perms.app.view_producto %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'listar_producto' %}">Listado Productos</a>
                        </li>
                        {% endif %}
                        -->
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">@{{ user.username }}</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registro' %}">Regístrate Ahora</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <!-- INCORPORACION FUNCION ELIMINAR PRODUCTO ###############################################-->
    <script>
        function eliminarProducto(id) {
            Swal.fire({
                    "title": "¿Está Seguro?",
                    "text": "Esta acción no se puede deshacer.",
                    "icon": "warning",
                    "showCancelButton": true,
                    "cancelButtonText": "No, Cancelar",
                    "confirmButtonText": "Si, ¡Eliminar!",
                    "reverseButtons": true,
                    "confirmButtonColor": "#397000"
                })
                .then(function (result) {
                    if (result.isConfirmed) {
                        window.location.href = "/eliminar-producto/" + id + "/"
                    }
                })
        }
    </script>

    {% load humanize %}

    <div class="row">
        <div class="col-12 col-md-8 offset-md-2">
            <div class="card">
                <div class="card-body">

                    <h2 style="font-weight: bolder; color: brown;">Listado de Productos</h2>
                    <hr>
                    <table class="table table-striped table-hover table-responsive-sm">

                        <tr>
                            <th>Nombre</th>
                            <th>Especie</th>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>¿Producto Nuevo?</th>
                            <th>Opciones</th>
                        </tr>

                        {% for p in productos %}

                        <tr>
                            <td>{{ p.nombre | title }}</td>
                            <td>{{ p.especie | title }}</td>
                            <td>{{ p.descripcion | title }}</td>
                            <td>${{ p.precio | intcomma }}</td>
                            <td>
                                {% if p.nuevo %}
                                SI
                                {% else %}
                                NO
                                {% endif %}
                            </td>
                            <td>
                                {% if perms.app.change_producto %}
                                <a href="{% url 'modificar_producto' p.id %}" class="btn btn-info btn-sm btn-danger"
                                    style="font-weight: bolder; color:goldenrod;">Modificar</a>
                                {% endif %}
                                <hr>
                                {% if perms.app.delete_producto %}
                                <a href="#" onclick="eliminarProducto({{ p.id }})" class="btn btn-info btn-sm btn-dark"
                                    style="font-weight: bolder; color:goldenrod;">Eliminar</a>
                                {% endif %}
                            </td>
                        </tr>

                        {% endfor %}

                    </table>

                    <!-- INCORPORACION SCRIPT SWEET ALERT ######################################-->
                    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

                    {% if messages %}
                    {% for m in messages %}
                    <script>
                        Swal.fire({
                            "title": "Felicidades",
                            "text": "{{m}}",
                            "icon": "success"
                        })
                    </script>
                    {% endfor %}
                    {% endif %}

                </div>
            </div>
        </div>
    </div>


    {% block js %}
    <!-- SCRIPT SEPARADOR ######################################################################-->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
    </script>
    {% endblock %}

</body>

</html>

Prueba4/app/templates/app/items/modificar.html
<!DOCTYPE html>
<html lang="EN">

<head>
    <meta charset="UTF-8">
    <title>Modificar Producto</title>
    <meta name="viewport" content="eidth=device-width, initial-scale=1">
    <!-- Hipervinculo a CSS ####################################################################-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/P1Css/Css3.css' %}">
    <!-- Invocar Formulario ####################################################################-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

{% load crispy_forms_tags %}

<body>
    <div id="wrapper">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <img src="{% static 'app/P1Img/Logo Icon.png' %}" alt="Icon" width="125" height="125"
                        class="d-inline-block">
                    Jardinería
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <!--
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                -->

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Volver Atrás</a>
                        </li>
                        <!--
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Nuestros Productos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'productos' %}#arbusto">Arbustos</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#flores">Flores</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#maceteros">Maceteros</a></li>
                                <li><a class="dropdown-item" href="{% url 'productos' %}#tierras">Tierra de Hojas</a>
                                </li>
                            </ul>
                        </li>
                        -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}#nosotros">¿Quiénes Somos?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'formulario' %}">Únete a Nosotros</a>
                        </li>
                        {% if perms.app.add_producto %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'agregar_producto' %}">Agregar Productos</a>
                        </li>
                        {% endif %}
                        {% if perms.app.view_producto %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'listar_producto' %}">Listado Productos</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">@{{ user.username }}</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registro' %}">Regístrate Ahora</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="row">
        <div class="col-12 col-md-8 offset-md-2">
            <div class="card" id="formulario">

                <div class="card-title">
                    <h2 style="font-weight: bold; color: brown;">MODIFICAR PRODUCTO</h2>
                </div>

                <div class="card-body">
                    <div class="container">

                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}

                            <table>
                                {{ form | crispy }}
                            </table>
                            <hr>
                            <br>
                            <center>
                                <h2 style="font-weight: bold; color:rgb(255, 145, 0)">{{mensaje}}</h2>
                            </center>

                            <br>
                            <div class="d-flex justify-content-end">
                                <input type="reset" value="Cancelar" class="btn btn-secondary">
                                &nbsp;
                                <input type="submit" value="Modificar" class="btn btn-primary">
                            </div>

                        </form>

                    </div>
                </div>

            </div>
        </div>
    </div>

    {% block js %}
    <!-- SCRIPT SEPARADOR ######################################################################-->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
    </script>
    {% endblock %}

</body>

</html>